// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0wIHlLeF9__TciSXKk-4nAWqjDKLlVeI',
    appId: '1:673333655420:web:d63fa5b282fa7f7adb16f9',
    messagingSenderId: '673333655420',
    projectId: 'logindemo-7ab17',
    authDomain: 'logindemo-7ab17.firebaseapp.com',
    storageBucket: 'logindemo-7ab17.appspot.com',
    measurementId: 'G-7GCSQJQXMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2e3Jm9mUfqSMHiChIcaLn4tS4zFDjZIE',
    appId: '1:673333655420:android:97fc7159157860a4db16f9',
    messagingSenderId: '673333655420',
    projectId: 'logindemo-7ab17',
    storageBucket: 'logindemo-7ab17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsIU0BSx3rFmRB0Q-6Sg4vKsXz-UoiMQI',
    appId: '1:673333655420:ios:a7bc72663efd079adb16f9',
    messagingSenderId: '673333655420',
    projectId: 'logindemo-7ab17',
    storageBucket: 'logindemo-7ab17.appspot.com',
    iosBundleId: 'com.example.loginTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsIU0BSx3rFmRB0Q-6Sg4vKsXz-UoiMQI',
    appId: '1:673333655420:ios:a7bc72663efd079adb16f9',
    messagingSenderId: '673333655420',
    projectId: 'logindemo-7ab17',
    storageBucket: 'logindemo-7ab17.appspot.com',
    iosBundleId: 'com.example.loginTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0wIHlLeF9__TciSXKk-4nAWqjDKLlVeI',
    appId: '1:673333655420:web:4ab1358df18c4687db16f9',
    messagingSenderId: '673333655420',
    projectId: 'logindemo-7ab17',
    authDomain: 'logindemo-7ab17.firebaseapp.com',
    storageBucket: 'logindemo-7ab17.appspot.com',
    measurementId: 'G-VX4JJ0NXC0',
  );
}
